/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const ANDORRA = {
    name: "Andorra",
    code: "AD",
    viewBox: "0 0 1000 835",
    states: [
        {
            name: "Ordino",
            code: "AD05",
            path: "M159.4 200.9l39.1-135.7 80.1 4.2 74.4-28.6 38.8-2.8 137.5 94.5 3.6 53 0 30.8-26.4 10.2-34 10.2-26.3 25.6-17 33.3-5.7 41-24.5-2.6-33.9-5.1-43.4-10.2-35.8-10.3-22.6-23-15.1-43.5-13.2-18-26.4-5.1-28.2 0-21-17.9z"
        },
        {
            name: "Canillo",
            code: "AD02",
            path: "M423.5 336.6l5.7-41 17-33.3 26.3-25.6 34-10.2 26.4-10.2 0-30.8-3.6-53 27.8 13.1 288.2 28.5-22 69.9 40.9 26 58.9 18.3 21.3 31.1 10.1 14.7-63.6 6-46.4 45.1-11.6 29.7-17.3-16.9-24.5-15.4-26.4-12.8-9.4-43.5-9.4-30.7-35.8 15.4-49 0-52.8 7.7-60.4 12.8-49 0-35.8 0-39.6 5.1z"
        },
        {
            name: "Encamp",
            code: "AD03",
            path: "M423.5 336.6l39.6-5.1 35.8 0 49 0 60.4-12.8 52.8-7.7 49 0 35.8-15.4 9.4 30.7 9.4 43.5 26.4 12.8 24.5 15.4 17.3 16.9-16.4 41.8-9.2 85.8-24.1 28.6-28.3 13.3-30.6 0.3-30.2-11-6.5-10.6-7.1-2.9-8.1-42-32.1-28.1-30.1-15.4-52.8-5.1-39.6 7.7-33.9-17.9-7.6-30.7-18.8-10.2-32.1 2.5 0-48.6-1.9-35.8z"
        },
        {
            name: "La Massana",
            code: "AD04",
            path: "M159.4 200.9l21 17.9 28.2 0 26.4 5.1 13.2 18 15.1 43.5 22.6 23 35.8 10.3 43.4 10.2 33.9 5.1 24.5 2.6 1.9 35.8 0 48.6-32 0-30.2 12.8-35.8 7.7-37.7 25.6-39.6 23-35.8 10.2-33.9 17.9-24.6 19.9-8.7-54.4-44.5-39.8-57.1 7.6 8.3-39.1 42-72.9 0.2-13.2-21.2-14.4 3.1-32.5 14.2-34.8 11.3-20.7 56-23z"
        },
        {
            name: "Sant Julià de Lòria",
            code: "AD06",
            path: "M155.8 538.1l24.6-19.9 33.9-17.9 35.8-10.2 3.8 30.7 1.9 20.4 9.4 33.3 15.1 15.3 43.3 10.2 34 12.8 47.1-7.7 41.5-5.1 26.3 5.1-16.9 30.7 3.7 35.8 7.5 41.8-71.6 9.3-14.1 16.2-11 19.7-16 19.5-29.4 16.2-20.7 2.9-153.5-20.5-29.1-21.7 0-43-73.1-114.4 43-19.6 14.4-3.7 50.1-36.2z"
        },
        {
            name: "Escaldes-Engordany",
            code: "AD08",
            path: "M425.4 421l32.1-2.5 18.8 10.2 7.6 30.7 33.9 17.9 39.6-7.7 52.8 5.1 30.1 15.4 32.1 28.1 8.1 42-7.6 3.8-9.2 10.8-27.5 92.7-81.2 34.4-88.2 11.5-7.5-41.8-3.7-35.8 16.9-30.7-26.3-5.1-41.5 5.1-47.1 7.7-34-12.8-43.3-10.2 20.7-12.8 30.2-17.9 20.7-35.8 15.1-28.1 13.2-17.9 28.3-28.1 16.9-28.2z"
        },
        {
            name: "Andorra la Vella",
            code: "AD07",
            path: "M250.1 490.1l39.6-23 37.7-25.6 35.8-7.7 30.2-12.8 32 0-16.9 28.2-28.3 28.1-13.2 17.9-15.1 28.1-20.7 35.8-30.2 17.9-20.7 12.8-15.1-15.3-9.4-33.3-1.9-20.4-3.8-30.7z"
        }
    ],
    labels: [
        {
            code: "AD05",
            x: "353.2",
            y: "183.5",
            name: "Ordino"
        },
        {
            code: "AD02",
            x: "679.2",
            y: "234.3",
            name: "Canillo"
        },
        {
            code: "AD03",
            x: "687.5",
            y: "411.8",
            name: "Encamp"
        },
        {
            code: "AD04",
            x: "188",
            y: "366.5",
            name: "La Massana"
        },
        {
            code: "AD06",
            x: "215.5",
            y: "668.9",
            name: "Sant Julià de Lòria"
        },
        {
            code: "AD08",
            x: "554.6",
            y: "586.1",
            name: "Escaldes-Engordany"
        },
        {
            code: "AD07",
            x: "308.5",
            y: "513.4",
            name: "Andorra la Vella"
        }
    ]
}

export default ANDORRA
