/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const ANGUILLA = {
    name: "Anguilla",
    code: "AI",
    viewBox: "0 0 1000 557",
    states: [
        {
            name: "East End",
            code: "AIX02",
            path: "M624.9 125.3l22.9-4.2-0.6 22.5 28.4 0 20.5-29.9 39.5-6.1 42.6 2.3-0.9 26-75.1 128.1-7.2 9.3 1.5-36.8-28.4 0 21-33.1 4.4-15.7-29.9-18.9-38.8 0 0.1-43.5z m207.6-69l28.2-10.7 11.3-20.3 52 10.7 30.5 19.1-23.7 9.5-48.6 14.3-9.1 13.1-35 23.8-12.4-13.1 14.7-19-7.9-27.4z"
        },
        {
            name: "Stoney Ground",
            code: "AIX10",
            path: "M624.9 125.3l-0.1 43.5 38.8 0 29.9 18.9-59.8 23.6-44.8-3.2-23.3 62.7-50.6 1.1-5 10.3-15.1-12.5 34.2-67.8 49.3-1.6 13.5-37.8-2.4-30.8 35.4-6.4z"
        },
        {
            name: "North Side",
            code: "AIX06",
            path: "M589.5 131.7l2.4 30.8-13.5 37.8-49.3 1.6-34.2 67.8-49-40.9 22.8-33.8 63.4-52.9 57.4-10.4z"
        },
        {
            name: "The Valley",
            code: "AIX13",
            path: "M494.9 269.7l15.1 12.5-10.8 22-96.7-18.3 18.6-20.3 24.8-36.8 49 40.9z"
        },
        {
            name: "North Hill",
            code: "AIX05",
            path: "M402.5 285.9l96.7 18.3-53.8 29.9-29.9-1.6-24.6 13 1.1-16.8-8.9-21.6 19.4-21.2z"
        },
        {
            name: "Sandy Ground",
            code: "AIX07",
            path: "M383.1 307.1l8.9 21.6-1.1 16.8-11.3 5.9-69.1 9.1 42.8-20.8 29.8-32.6z"
        },
        {
            name: "South Hill",
            code: "AIX09",
            path: "M390.9 345.5l24.6-13 29.9 1.6-42.5 27.7-32.3 21.1-23.9 20.4-53.8 1.6-3 17.3-41.9 0 0.2 27.7-32.9 24.7-0.7-96.8 95.9-17.3 69.1-9.1 11.3-5.9z"
        },
        {
            name: "West End",
            code: "AIX14",
            path: "M214.6 377.8l0.7 96.8-53.4 40.2-51.4 17.1-65-1 96.7-113.8 29-23.5 43.4-15.8z"
        },
        {
            name: "Blowing Point",
            code: "AIX01",
            path: "M248.2 449.9l-0.2-27.7 41.9 0 3-17.3 53.8-1.6 23.9-20.4 32.3-21.1 1.9 37.1 25-12.1 15.5-26.4-0.2 53.9-143.2 89.6-10.7-16.7-25.3-18.3-17.7-19z"
        },
        {
            name: "The Farrington",
            code: "AIX11",
            path: "M445.4 334.1l53.8-29.9 47.8-4.8 10.5 12.6 3.8 38.4-27.2 8.2-89 55.7 0.2-53.9 0.1-26.3z"
        },
        {
            name: "Sandy Hill",
            code: "AIX08",
            path: "M693.5 187.7l-4.4 15.7-21 33.1 28.4 0-1.5 36.8-21.6 28.3-41.2 27.4-70.9 21.4-3.8-38.4-10.5-12.6 18.6-28.6 23.3-62.7 44.8 3.2 59.8-23.6z"
        },
        {
            name: "Island Harbour",
            code: "AIX04",
            path: "M696.1 113.7l-20.5 29.9-28.4 0 0.6-22.5 48.3-7.4z"
        },
        {
            name: "George Hill",
            code: "AIX03",
            path: "M402.9 361.8l42.5-27.7-0.1 26.3-15.5 26.4-25 12.1-1.9-37.1z"
        },
        {
            name: "The Quarter",
            code: "AIX12",
            path: "M510 282.2l5-10.3 50.6-1.1-18.6 28.6-47.8 4.8 10.8-22z"
        }
    ],
    labels: [
        {
            code: "AIX02",
            x: "714.8",
            y: "154.7",
            name: "East End"
        },
        {
            code: "AIX10",
            x: "544.5",
            y: "236.3",
            name: "Stoney Ground"
        },
        {
            code: "AIX06",
            x: "553",
            y: "169.7",
            name: "North Side"
        },
        {
            code: "AIX13",
            x: "454.9",
            y: "268.6",
            name: "The Valley"
        },
        {
            code: "AIX05",
            x: "429.8",
            y: "312.1",
            name: "North Hill"
        },
        {
            code: "AIX07",
            x: "375.9",
            y: "337.3",
            name: "Sandy Ground"
        },
        {
            code: "AIX09",
            x: "268.3",
            y: "395.2",
            name: "South Hill"
        },
        {
            code: "AIX14",
            x: "151.2",
            y: "468.2",
            name: "West End"
        },
        {
            code: "AIX01",
            x: "326.4",
            y: "441.5",
            name: "Blowing Point"
        },
        {
            code: "AIX11",
            x: "496.2",
            y: "344.1",
            name: "The Farrington"
        },
        {
            code: "AIX08",
            x: "621.8",
            y: "271.3",
            name: "Sandy Hill"
        },
        {
            code: "AIX04",
            x: "668.2",
            y: "130.8",
            name: "Island Harbour"
        },
        {
            code: "AIX03",
            x: "423.5",
            y: "367.1",
            name: "George Hill"
        },
        {
            code: "AIX12",
            x: "531.3",
            y: "286.3",
            name: "The Quarter"
        }
    ]
}

export default ANGUILLA
