/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const ANTIGUA_AND_BARBUDA = {
    name: "Antigua_and_barbuda",
    code: "AG",
    viewBox: "0 0 1000 1000",
    states: [
        {
            name: "Saint Paul",
            code: "AG06",
            path: "M807.2 833.1l-8.5 4.1-0.4 10.4 5.2 28-8.2 13.6-17.9-8.6-17.7-16.1-7.7-8.7-7.3 1.9-22.4 10.9-7.5-18.4 3.4-12.8-7.8-15.1 8.9-9.3 24.5-7 11.1 2.3 27.8 0 16.7-4.7 7.8 29.5z"
        },
        {
            name: "Saint Philip",
            code: "AG08",
            path: "M807.2 833.1l-7.8-29.5 5.6-22.1 14.6-10.7 14.4-0.4 14.8-8.1 8.1 0 5.6 5.6 3.7 5.7 5 12.8-7.4-0.6-15 1.1-7.5-0.5 10.2 12.7 9.3 6.1 5.4 6.1-2.5 13.3-12.3 19.8-12.3 0.8-14.1-7.2-17.8-4.9z"
        },
        {
            name: "Saint Peter",
            code: "AG07",
            path: "M799.4 803.6l-16.7 4.7-27.8 0 0-12.8 7.8-16.3 12.2-4.7-1.1-11.6-5.6-9.3 6.1-6.9 1.1-10.1 2.9-6.7 10.3-14.4 6.2 9.8 8.5 5.7 10.6 1.8 12.5-1.7-5.3 6.1-3 4.2-4.7 3.1-9.9 2.2 5 16.4 11.1 7.7-14.6 10.7-5.6 22.1z"
        },
        {
            name: "Saint George",
            code: "AG03",
            path: "M774.3 746.7l-6.1 6.9 5.6 9.3 1.1 11.6-12.2 4.7-7.8 16.3-7.8-3.5-15.6-10.5 2.2-12.8-3.3-24.4-8.9-8.2-1.1-23.3 15.6-1.1-2-22.9 13.8 20.3 8.4 23.5 18.1 14.1z"
        },
        {
            name: "Saint John",
            code: "AG04",
            path: "M754.9 808.3l-11.1-2.3-24.5 7-8.9 9.3-5.6-12.8-16.7 18.6 4.5-29.1 5.5-12.8-1.1-3.5-18.9-4.7-10-9.3-13.5 9.2-7.8-3.1-22.7-12.5 12-11.4 19.4-8.3 25.1-7.6-8.9-15.1 1.9-13.5 9.9-11.8 15.7-10.2 34.8 4.4 2 22.9-15.6 1.1 1.1 23.3 8.9 8.2 3.3 24.4-2.2 12.8 15.6 10.5 7.8 3.5 0 12.8z"
        },
        {
            name: "Saint Mary",
            code: "AG05",
            path: "M710.4 822.3l7.8 15.1-3.4 12.8 7.5 18.4-15 2.7-22.7 0.2-14.2-3.2-34.9-21.3-7.3-10.4 7.4-15.5 4.8-13.1-3.9-11.1 0.4-9.8 17.7-9.2 13.5-9.2 10 9.3 18.9 4.7 1.1 3.5-5.5 12.8-4.5 29.1 16.7-18.6 5.6 12.8z"
        },
        {
            name: "Barbuda",
            code: "AG10",
            path: "M684.3 199.2l-14 7.8-6-16.5-2.3-46.7-4.9-21-6.4-17.6-4.5-17.9 0.9-22.3 4 3.7 1.7 3.8 1.8 8.8 6.6 13.9 17.3 20.9 5.8 12.1-0.3 16-4.3 13.6 0 10.7 12.8 7.3 5.4-21.4 1.6-29.1-6.8-25.8-19.6-11-7.9-12.6 5.2-22 15.1-8.4 21.8 28-7.3 4.4-7.5 3.4 14.4 5.2 22.8-8 14.2 2.8 17.6 13.4 15.1 18.2 12 19.9 8.1 18.9 7.8 34.2 1 18.9-2 17.9-7.4 21.5-7.5 3.9-11.2-1-18.6 6.8-6.9-20.5-19.4-14.5-48.2-19.7z"
        },
        {
            name: "Redonda",
            code: "AG11",
            path: "M131.7 946.4l1.1-1.5 1.7-0.5 0.2 2.9-0.2 3.7-1.5 2.9-2.9 0.6-1.3-1.9 1.1-4.2 1.8-2z"
        }
    ],
    labels: [
        {
            code: "AG06",
            x: "771.6",
            y: "836",
            name: "Saint Paul"
        },
        {
            code: "AG08",
            x: "826.9",
            y: "809.1",
            name: "Saint Philip"
        },
        {
            code: "AG07",
            x: "791.1",
            y: "766.2",
            name: "Saint Peter"
        },
        {
            code: "AG03",
            x: "749.3",
            y: "750.4",
            name: "Saint George"
        },
        {
            code: "AG04",
            x: "699.9",
            y: "752.9",
            name: "Saint John"
        },
        {
            code: "AG05",
            x: "663.6",
            y: "820.8",
            name: "Saint Mary"
        },
        {
            code: "AG10",
            x: "746.4",
            y: "167.7",
            name: "Barbuda"
        },
        {
            code: "AG11",
            x: "132.1",
            y: "950",
            name: "Redonda"
        }
    ]
}

export default ANTIGUA_AND_BARBUDA
