/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const BAHRAIN = {
    name: "Bahrain",
    code: "BH",
    viewBox: "0 0 1000 1000",
    states: [
        {
            name: "Al Manāmah",
            code: "BH13",
            path: "M388.7 104l14.4 3 18.6 8.5 15 6.9 0.1-0.1 47.6-18.9 7.6 5 4.8 16.8 8.5 11.6 2.5 5.3 2.5 5.3-6.5 13.7-10.9 3.1-32.9-4.7-16.2 6-19.1-24.8-38.1-3.4 2.1-33.3z"
        },
        {
            name: "Ash Shamālīyah",
            code: "BH17",
            path: "M388.7 104l-2.1 33.3 38.1 3.4 19.1 24.8-34.3 7.6-13.8 13.6 16.8 62.9 7.6 32.3 9.2 61.2-27.5 11.9-28.1-1.3-6.6-48.4-17.6-47.6-19.6-34.7-4.7-15.5 0.7-21 13.5-60.9 8.4-15 15-7.3 0.2 0 1.1 0 24.6 0.7z m-122.7 86.6l12.4 4.2 12.4 6.9 0 22.1 2.5 18 2.5 19.3-21.1-5.5-22.3 1.4-6.2-20.8 2.5-26.2 17.3-19.4z"
        },
        {
            name: "Al Janūbīyah",
            code: "BH14",
            path: "M373.7 353.7l28.1 1.3 27.5-11.9-9.2-61.2-7.6-32.3-16.8-62.9 13.8-13.6 34.3-7.6 49.9 43.7 11.7-18.6 17.4-13.8 7.4 19.4 7.4 30.4 14.9 1.3-11.7 14.7-0.7 24-23.3 5.9 1.8 19.6 5 55.2-2.6 113.4-17.2 141.6-10.4 28-33.6 55.2-0.2 0.3-7.7-38.9-13.1-42.5-18.3-41.5-23.1-35.7-50.4-57.3-8.5-35.6 22.6-43.1 6.3-18.8 6.3-18.7z m337 420.8l9.5-7.3 11.7-6.5 0 8.1-2.9 11.3-8.8 13-8.8 11.4 5.9 5.7 8.7 9.7-4.4 6.5-13.8-3.2-6.6 4.8-9.5 9-4.4 4.8 5.1 17.1 8.8 12.1 2.2 8.1-8.1 3.3-4.4 8.1-1.4 10.5 6.6 4.9 5.1 7.3-7.3 7.3-6.6 11.3-5.9 11.4 3 8.1-3.7 3.2-13.2-6.4-8.7-13.8 4.4-12.2 8.7-20.3-0.7-12.1 0-17.9-10.2-11.3 0.7-11.4 1.5-15.4 4.3-17 11.7-18.7 15.4-18.7 6.6-6.5 9.5 1.7z m0.7-45.5l8.1 0.8 1.4 8.1-12.4 4.9-5.9-9.7 8.8-4.1z m42.4 99l-3.6 12.2-9.5 6.5-5.2-7.3-2.2-6.5 3-5.7 17.5 0.8z m-23.4 34.9l13.9 2.4 5.9 6.5-1.5 9.8-4.4 6.5-4.4-1.7-5.8-1.6-8.1 1.6-5.8 3.3-5.1-10.6 2.2-6.5-3.7-5.6 2.2-5.7 7.3 0.8 7.3 0.8z"
        },
        {
            name: "Al Muḩarraq",
            code: "BH15",
            path: "M501.7 56.5l35.9-11 26.1 13.8 1.2 19.4 0 19.3 17.4 24.9 14.9 6.9-6.2 18-6.2 6.9-18.6-11.1-5-17.9-6.2-18-16.1-4.2-14.9-2.7-9.9 4.1-14.9-27.6 2.5-20.8z"
        }
    ],
    labels: [
        {
            code: "BH13",
            x: "454.3",
            y: "138.5",
            name: "Al Manāmah"
        },
        {
            code: "BH17",
            x: "368.3",
            y: "217.7",
            name: "Ash Shamālīyah"
        },
        {
            code: "BH14",
            x: "437.8",
            y: "438.8",
            name: "Al Janūbīyah"
        },
        {
            code: "BH15",
            x: "541.5",
            y: "78.3",
            name: "Al Muḩarraq"
        }
    ]
}

export default BAHRAIN
