/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const BERMUDA = {
    name: "Bermuda",
    code: "BM",
    viewBox: "0 0 1000 698",
    states: [
        {
            name: "Hamilton",
            code: "BMHAM",
            path: "M734.3 269.2l-29.6-29.7-43.8 17.4-31.6 22.8-7 27.2-18.1-4.4-8.3-19.8 20.1-48.5 54.8-39.3 53.1 4.3 11.9 38.5 38.4 14-39.9 17.5z m-32.5 29.8l32.5-29.8 26.6 43.8-33.9 23.3-25.2-37.3z m-109.7 34.8l9.2-10.4 16.2 5.3 18.2-1-32.2 27.7-11.4-21.6z"
        },
        {
            name: "Smith's",
            code: "BMSMI",
            path: "M701.8 299l25.2 37.3-37.1 25.6-79.7 60.4-39.1-64.9 21-23.6 11.4 21.6 32.2-27.7 48.3-2.5 17.8-26.2z"
        },
        {
            name: "Devonshire",
            code: "BMDEV",
            path: "M571.1 357.4l39.1 64.9-10.2 7.7-54.5 33-22.6 31.3-23.5-46-46 23.8-4.2-55.5 69.8-34 40.5-12.1 11.6-13.1z"
        },
        {
            name: "Pembroke",
            code: "BMPEM",
            path: "M449.2 416.6l4.2 55.5-20.6 2.4 0-30.6-35.8 4.4-2.7 30.8-41.4-17.5-32.7-47.6 11.9-16.2 117.1 18.8z"
        },
        {
            name: "City of Hamilton",
            code: "BMHA",
            path: "M394.3 479.1l2.7-30.8 35.8-4.4 0 30.6-38.5 4.6z"
        },
        {
            name: "Paget",
            code: "BMPAG",
            path: "M453.4 472.1l46-23.8 23.5 46-11.8 16.3-73.9 68.2-19.2 9.8-33.5-62.3 61.7-38.1 7.2-16.1z m-109.3 21l29.5 14-10.3 10.5-32.6-5.3 13.4-19.2z"
        },
        {
            name: "Warwick",
            code: "BMWAR",
            path: "M384.5 526.3l33.5 62.3-79.9 40.9-22.5 8.7-21.1-34.4-46.5 9.9 14.7-31.4 35.5-3.5 63.6-38.5 22.7-14z m-40.4-33.2l-13.4 19.2-35.4 5.3-35.5-3.5-10.4-24.5 11.9-8.7 32.5 8.7 20.7-7 13.3-5.2 16.3 15.7z"
        },
        {
            name: "Southampton",
            code: "BMSOU",
            path: "M248 613.7l46.5-9.9 21.1 34.4-72.1 28-57.6-1.8-44.4-1.7-59.1-40.2-14.7-36.9 65-13.8-4.5 29.7 25.2 34.9 41.4 0 53.2-22.7z"
        },
        {
            name: "Sandys",
            code: "BMSAN",
            path: "M132.7 571.8l-65 13.8-10.4-26.1-11.8-48.9 35.7 16.5-5.2-32.3 13.1-43.4-20-44 28.1 10.5 13.3-26.2 17.7 26.2 23.7 24.5-34 29.7-10.7 51.1-8.5 15.4 19.2 15.7 69.5 8.7 0 14-54.7-5.2z"
        },
        {
            name: "Saint George's",
            code: "BMSGE",
            path: "M734.3 269.2l39.9-17.5 65 24.5-78.3 36.8-26.6-43.8z m-10.4-70l-53.1-4.3 33.9-53.4 60.6-41.4 80.7-68.4 108.5 92.3-29.5 40.2-1.5 40.3-17.7-14-26.6-24.5-51.1-12.7-16.9 19.7-23.7-29.8-63.6 56z m118.7-82.2l32.4-20.2-13.7-30.4-34.1 22.3 15.4 28.3z"
        },
        {
            name: "City of Saint George",
            code: "BMSG",
            path: "M842.6 117l-15.4-28.3 34.1-22.3 13.7 30.4-32.4 20.2z"
        }
    ],
    labels: [
        {
            code: "BMHAM",
            x: "677.5",
            y: "222.9",
            name: "Hamilton"
        },
        {
            code: "BMSMI",
            x: "638",
            y: "364.4",
            name: "Smith's"
        },
        {
            code: "BMDEV",
            x: "529.7",
            y: "423.5",
            name: "Devonshire"
        },
        {
            code: "BMPEM",
            x: "373.2",
            y: "437.3",
            name: "Pembroke"
        },
        {
            code: "BMHA",
            x: "414.2",
            y: "461.5",
            name: "City of Hamilton"
        },
        {
            code: "BMPAG",
            x: "449.2",
            y: "524.5",
            name: "Paget"
        },
        {
            code: "BMWAR",
            x: "344.6",
            y: "588.4",
            name: "Warwick"
        },
        {
            code: "BMSOU",
            x: "239.9",
            y: "641.6",
            name: "Southampton"
        },
        {
            code: "BMSAN",
            x: "113",
            y: "441.5",
            name: "Sandys"
        },
        {
            code: "BMSGE",
            x: "805.3",
            y: "115.9",
            name: "Saint George's"
        },
        {
            code: "BMSG",
            x: "851.5",
            y: "92.1",
            name: "City of Saint George"
        }
    ]
}

export default BERMUDA
