/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const COMOROS = {
    name: "Comoros",
    code: "KM",
    viewBox: "0 0 1000 791",
    states: [
        {
            name: "Moûhîlî",
            code: "KMM",
            path: "M443.1 704.3l5.7 2.5 36.7 24.4 7.9 12.2-2.4 5.7-10.5 1.5-16.3 0-46.9-9.6-48.4-1.3-11.2-4-3-5.3 0.7-12.2-2-6.6-6-5.7-6.3-2.8-5-3.7-2-9.4-0.8-25.5 4.1-10.5 11.3 4 9.8 5.3 29 5.6 13.1 4 36 24 6.5 7.4z"
        },
        {
            name: "Andjouân",
            code: "KMA",
            path: "M954.5 651.1l-0.3 86.2-3.9 12.8-7.9 5.3-6.1-2.5-7.1-6-5.7-7.3-2.4-6.1-1.3-8.8-3.8-5-50.9-35.3-5.7-9.1-4.2-10.8-10.5-5.3-27.3-5.6-42.9-22.1-5.8-4.7-27.8-16.6-9.3-10.1 11.1-0.4 9.3 2.3 17.7 7.7 12.1 3.1 22.3 3.3 8.1 3.3 3.7-3 6.9-3.6 3.6-3.1 20.7 4.3 18.3-16.8 10.5-26.3-2.4-23.9 6.8-2 9.5-5.6 7.4-2 3.4-1.5 3-2.3 3.3-1.7 4.8 0.2 4 2.9 5.4 9.8 2.4 2.2 29.2 94.2 1.8 9.9z"
        },
        {
            name: "Andjazîdja",
            code: "KMG",
            path: "M220.5 360.7l1.7 7.1 4.4 8 16.1 21.6-0.3 5.9-7.8 12.6-2.3 7.1-0.7 5.1-1.8 4-5.1 3.6-6.6 2.1-9.4 1.4-8.2-0.9-3.6-5.3-4.5-8.9-38.7-35.9-10.2-4.3-29.6-1.7-7.3-1.8-7.9-4.4-13.3-10.7-5.6-7.2-2-6.2-0.9-6.2-3.1-6.9-17.6-17.2-7.6-11.3-3.1-17.3 1.9-6.9 4.5-8.5 14.9-21.9 0.2-7.5-2-7.6-0.7-8.2 9.6-124.7-1.5-8.2-3.7-7.6 6.7-12.2 6.6-17.3 7.2-13.5 8.1-0.3 29.4-10 17.2-2.6 12.7 5.1 8.2 10.9 6.1 11.4 3.2 12.8-15.4 131.7 6.2 28.5 30.7 44.2 11.1 28.9 0.3 7.2-1 14.9 0.7 7.2 3.2 5.2 4.5 4.5 4.2 5.1 1.9 7.1z"
        }
    ],
    labels: [
        {
            code: "KMM",
            x: "386.8",
            y: "704.4",
            name: "Moûhîlî"
        },
        {
            code: "KMA",
            x: "897",
            y: "637.5",
            name: "Andjouân"
        },
        {
            code: "KMG",
            x: "117.9",
            y: "294.4",
            name: "Andjazîdja"
        }
    ]
}

export default COMOROS
