/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const GRENADA = {
    name: "Grenada",
    code: "GD",
    viewBox: "0 0 1000 1000",
    states: [
        {
            name: "Saint George",
            code: "GD03",
            path: "M370.3 915.7l-10.7 9.7-6.9 12.9-2.5 16.2-15.7-2.9-15.2-4.7-14.3-6.5-13.3-8.2-17.5 15.3-28.6 6.1-31.3-1.6-25.3-7 58.5-37.7 10.7-10.5 5.9-25.2-4.8-20.2-8.3-19.8-4.5-23.6 9.1-38.4 59.1 0.1 49.9-1.5 8.3 34.1 8.3 11.3-22.2 7.1-11 38.3 0 29.8 12.4 19.8 9.9 7.1z"
        },
        {
            name: "Saint David",
            code: "GD02",
            path: "M370.3 915.7l-9.9-7.1-12.4-19.8 0-29.8 11-38.3 22.2-7.1 30.5-8.5 26.4 11.4 30.8 23.9-2 13.5-0.6 14.1-9.3 15.4-72.3 38 0-12.8-14.4 7.1z"
        },
        {
            name: "Saint Andrew",
            code: "GD01",
            path: "M381.2 813.6l-8.3-11.3-8.3-34.1-2.8-18.4 19.4-24.1 23.6-39.7 11.1-35.5 41.6 0 47.3 4.3-5.2 74-4.1 12.1-7.4 11.9-11.2 26.4 0.5 13.4 9.5 28.2-4.3 5.4-8.7 4-5 10.2-30.8-23.9-26.4-11.4-30.5 8.5z"
        },
        {
            name: "Saint Patrick",
            code: "GD06",
            path: "M504.8 654.8l-47.3-4.3-41.6 0-5.5-35.5-16.7-24.1-21.9-16.6 18-21.9 35.3-6.4 38.5 5.2 36.5 23.1-1.1 5.3-10.6 10.1 14.1 29.3 3.1 25-0.8 10.8z"
        },
        {
            name: "Saint Mark",
            code: "GD05",
            path: "M415.9 650.5l-11.1 35.5-25-19.9-31.8-15.6-31.9-8.2 55.7-68 21.9 16.6 16.7 24.1 5.5 35.5z"
        },
        {
            name: "Saint John",
            code: "GD04",
            path: "M364.6 768.2l-49.9 1.5-59.1-0.1 35-67.6 1.1-29.9 24.4-29.8 31.9 8.2 31.8 15.6 25 19.9-23.6 39.7-19.4 24.1 2.8 18.4z"
        },
        {
            name: "Carriacou and Petite Martinique",
            code: "GD10",
            path: "M800.1 175.1l-29.7-8.9-28.4 8.1-28.2 14.5-28.6 11 5.8-10.6 11.3-27.2 5.8-10.5-5.2-0.9-17.7 0.9 2.4-6.9 10-16.7 36.4 11.1 21.8-29.8 18.3-41 26-22.7 10.9 28.2-2.9 31.4-6.9 34.2-1.1 35.8z"
        }
    ],
    labels: [
        {
            code: "GD03",
            x: "302.3",
            y: "858.7",
            name: "Saint George"
        },
        {
            code: "GD02",
            x: "403.7",
            y: "859.4",
            name: "Saint David"
        },
        {
            code: "GD01",
            x: "437.4",
            y: "737.5",
            name: "Saint Andrew"
        },
        {
            code: "GD06",
            x: "447.4",
            y: "595.9",
            name: "Saint Patrick"
        },
        {
            code: "GD05",
            x: "375.6",
            y: "625.3",
            name: "Saint Mark"
        },
        {
            code: "GD04",
            x: "337.2",
            y: "704",
            name: "Saint John"
        },
        {
            code: "GD10",
            x: "771.5",
            y: "135",
            name: "Carriacou and Petite Martinique"
        }
    ]
}

export default GRENADA
