/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const LIECHTENSTEIN = {
    name: "Liechtenstein",
    code: "LI",
    viewBox: "0 0 1000 1000",
    states: [
        {
            name: "Triesen",
            code: "LI09",
            path: "M462.8 941l-2.9-29.3-8.1-36-19.7-33.6-1.6-35.9-29.4-7.2-27.3-26.9 28-57.6-1.6-92.1 45-5.9 18 24 3.3 43.2 8.1 52.9 31.1 24 26.1 4.8 11.4 31.2-17.9 26.4 17.9 31.1 29.5 0 3.2-31.1-11.4-24 44.1 7.2 4.9 50.3 11.2 52.4-20.7 26.4-60.4 19.2-80.8-13.5z"
        },
        {
            name: "Schaan",
            code: "LI07",
            path: "M674.3 845.9l-49.6 63-11.2-52.4-4.9-50.3 44.1-16.8 8.2 35.9 13.4 20.6z m12.9-193.5l13.6 50.6-41.6-0.1-24.5-2.4-17.9 7.3-27.8 4.8-6.5-64.9-11.5-40.8-26.1-19.2 6.5-45.7 27.8 16.9 22.9 24 27.7 31.2 26.2 43.2 31.2-4.9z m-169.1-229.6l0.3 37.5-11.1 26.5-29.4-7.2-37.6-12-22.9 16.8-14.7-26.4-21.2-7.3 8.2 69.7-37.4-12.8-8.5-16.7-22.5-71.5 4.3-88.9 39.6 21.7 50.6 2.4 40.9-14.4-3.3 38.4 32.7 36.1 32 8.1z"
        },
        {
            name: "Triesenberg",
            code: "LI10",
            path: "M700.8 703l4.6 17-20.3 112.2-10.8 13.7-13.4-20.6-8.2-35.9 1.6-36-19.6-52.9 24.5 2.4 41.6 0.1z m-157.6 93.6l-11.4-31.2-26.1-4.8-31.1-24-8.1-52.9-3.3-43.2-18-24 1.6-52.8 11.5-12 31 0 9.8-26.5 8.2-38.4 21.2 31.2 22.9 24-6.5 45.7 26.1 19.2 11.5 40.8 6.5 64.9-22.9 4.8 1.7 40.8-3.3 40.8-21.3-2.4z"
        },
        {
            name: "Balzers",
            code: "LI01",
            path: "M562.6 486.5l43.2 25.6 69.9 97.8 11.5 42.5-31.2 4.9-26.2-43.2-27.7-31.2-22.9-24-27.8-16.9 11.2-55.5z m-99.8 454.5l-98.7-16.4-66.2-19.6-3.3-40.3 34.3-46.2 44.9-46.4 27.3 26.9 29.4 7.2 1.6 35.9 19.7 33.6 8.1 36 2.9 29.3z m101.7-142l11.4 24-3.2 31.1-29.5 0-17.9-31.1 17.9-26.4 21.3 2.4z"
        },
        {
            name: "Planken",
            code: "LI05",
            path: "M518.4 460.3l44.2 26.2-11.2 55.5-22.9-24-21.2-31.2 11.1-26.5z m28.8-102.5l-29.1 65-32-8.1-32.7-36.1 3.3-38.4 26.1-21.7 34.3 9.6 30.1 29.7z"
        },
        {
            name: "Eschen",
            code: "LI02",
            path: "M525.1 266.9l25.2 60.1-3.1 30.8-30.1-29.7-34.3-9.6-26.1 21.7-36-21.7-27.8-21.6-3.2-43.3 13-43.3 21.3-2.4 14.7 36.1 50.6 26.4 35.8-3.5z"
        },
        {
            name: "Mauren",
            code: "LI04",
            path: "M492.1 166.6l-8 24.7 13 38 28 37.6-35.8 3.5-50.6-26.4-14.7-36.1 29.4-28.9 38.7-12.4z"
        },
        {
            name: "Schellenberg",
            code: "LI08",
            path: "M465.9 95.8l37.9 35.2-11.7 35.6-38.7 12.4-29.4 28.9-1.7-26.5 19.6-28.9 9.9-28.8 14.1-27.9z"
        },
        {
            name: "Ruggell",
            code: "LI06",
            path: "M465.9 95.8l-14.1 27.9-9.9 28.8-19.6 28.9 1.7 26.5-21.3 2.4-26.1-12-19.9-6.3 22.3-64 48.6-82.5 26.7 39.6 11.6 10.7z"
        },
        {
            name: "Vaduz",
            code: "LI11",
            path: "M445.2 616.5l-45 5.9-24.5-69.2-23.4-45.6 37.4 12.8-8.2-69.7 21.2 7.3 14.7 26.4 22.9-16.8 37.6 12 29.4 7.2-8.2 38.4-9.8 26.5-31 0-11.5 12-1.6 52.8z m163.4 189.7l-44.1-7.2 3.3-40.8-1.7-40.8 22.9-4.8 27.8-4.8 17.9-7.3 19.6 52.9-1.6 36-44.1 16.8z"
        },
        {
            name: "Gamprin",
            code: "LI03",
            path: "M456.7 340.2l-40.9 14.4-50.6-2.4-39.6-21.7 2.7-56.6 28.4-81.9 19.9 6.3 26.1 12-13 43.3 3.2 43.3 27.8 21.6 36 21.7z"
        }
    ],
    labels: [
        {
            code: "LI09",
            x: "479.7",
            y: "817.1",
            name: "Triesen"
        },
        {
            code: "LI07",
            x: "421.8",
            y: "410.2",
            name: "Schaan"
        },
        {
            code: "LI10",
            x: "519.3",
            y: "657.8",
            name: "Triesenberg"
        },
        {
            code: "LI01",
            x: "381.4",
            y: "859.1",
            name: "Balzers"
        },
        {
            code: "LI05",
            x: "498.6",
            y: "370.4",
            name: "Planken"
        },
        {
            code: "LI02",
            x: "454.8",
            y: "295.7",
            name: "Eschen"
        },
        {
            code: "LI04",
            x: "462.6",
            y: "216.3",
            name: "Mauren"
        },
        {
            code: "LI08",
            x: "471.4",
            y: "139.8",
            name: "Schellenberg"
        },
        {
            code: "LI06",
            x: "415.9",
            y: "129.7",
            name: "Ruggell"
        },
        {
            code: "LI11",
            x: "428.1",
            y: "526.9",
            name: "Vaduz"
        },
        {
            code: "LI03",
            x: "361.2",
            y: "293.7",
            name: "Gamprin"
        }
    ]
}

export default LIECHTENSTEIN
