/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const NAURU = {
    name: "Nauru",
    code: "NR",
    viewBox: "0 0 1000 1000",
    states: [
        {
            name: "Anetan",
            code: "NR03",
            path: "M478.8 88.8l112.7-43.3 2.6 203.7-115.3-160.4z"
        },
        {
            name: "Ewa",
            code: "NR09",
            path: "M478.8 88.8l115.3 160.4-13.9 93.8-191.2-219.7 89.8-34.5z"
        },
        {
            name: "Baiti",
            code: "NR05",
            path: "M389 123.3l191.2 219.7-6.9 46.5-5.1 42.2-283.6-268.2 104.4-40.2z"
        },
        {
            name: "Uaboe",
            code: "NR13",
            path: "M284.6 163.5l283.6 268.2-6.5 54.5-345.9-296.3 68.8-26.4z"
        },
        {
            name: "Nibok",
            code: "NR12",
            path: "M215.8 189.9l345.9 296.3-4 33.2-5.8 40.7-113.7-35.5-119.5-31.2-148.9-126.9 46-176.6z"
        },
        {
            name: "Denigomodu",
            code: "NR08",
            path: "M169.8 366.5l148.9 126.9-51.9 52-146.1 9.4 49.1-188.3z"
        },
        {
            name: "Aiwo",
            code: "NR01",
            path: "M120.7 554.8l146.1-9.4-10.4 72.7 26 88.3-87.7 27.9-74-179.5z"
        },
        {
            name: "Boe",
            code: "NR06",
            path: "M194.7 734.3l87.7-27.9 32.2 55-27 22.9-28.4 106.4-64.5-156.4z"
        },
        {
            name: "Yaren",
            code: "NR14",
            path: "M259.2 890.7l28.4-106.4 27-22.9 76.9-65.4 108.7 241-241-46.3z"
        },
        {
            name: "Meneng",
            code: "NR11",
            path: "M500.2 937l-108.7-241 150.6-67.5 145.5 36.4 116.8 16.4-27.5 85.4-185.4 187.8-91.3-17.5z"
        },
        {
            name: "Anibare",
            code: "NR04",
            path: "M580.2 343l13.9-93.8 114.3 67.6 158.1 38.1 12.8 93.9-74.9 232.5-116.8-16.4-145.5-36.4 9.8-68.4 5.8-40.7 4-33.2 6.5-54.5 5.1-42.2 6.9-46.5z"
        },
        {
            name: "Ijuw",
            code: "NR10",
            path: "M866.5 354.9l-158.1-38.1-114.3-67.6 245.4-91.8 27 197.5z"
        },
        {
            name: "Anabar",
            code: "NR02",
            path: "M594.1 249.2l-2.6-203.7 248 111.9-245.4 91.8z"
        },
        {
            name: "Buada",
            code: "NR07",
            path: "M318.7 493.4l119.5 31.2 113.7 35.5-9.8 68.4-150.6 67.5-76.9 65.4-32.2-55-26-88.3 10.4-72.7 51.9-52z"
        }
    ],
    labels: [
        {
            code: "NR03",
            x: "550.9",
            y: "117.2",
            name: "Anetan"
        },
        {
            code: "NR09",
            x: "506.9",
            y: "197.9",
            name: "Ewa"
        },
        {
            code: "NR05",
            x: "444.3",
            y: "257.4",
            name: "Baiti"
        },
        {
            code: "NR13",
            x: "397.3",
            y: "307.7",
            name: "Uaboe"
        },
        {
            code: "NR12",
            x: "334",
            y: "394.3",
            name: "Nibok"
        },
        {
            code: "NR08",
            x: "207.1",
            y: "482.7",
            name: "Denigomodu"
        },
        {
            code: "NR01",
            x: "207.4",
            y: "630.5",
            name: "Aiwo"
        },
        {
            code: "NR06",
            x: "250.9",
            y: "760.8",
            name: "Boe"
        },
        {
            code: "NR14",
            x: "365.6",
            y: "831",
            name: "Yaren"
        },
        {
            code: "NR11",
            x: "588.2",
            y: "773.4",
            name: "Meneng"
        },
        {
            code: "NR04",
            x: "708.6",
            y: "482.7",
            name: "Anibare"
        },
        {
            code: "NR10",
            x: "771.2",
            y: "257.5",
            name: "Ijuw"
        },
        {
            code: "NR02",
            x: "662.8",
            y: "150.6",
            name: "Anabar"
        },
        {
            code: "NR07",
            x: "380.2",
            y: "607.5",
            name: "Buada"
        }
    ]
}

export default NAURU
