/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const SAINT_LUCIA = {
    name: "Saint_lucia",
    code: "LC",
    viewBox: "0 0 1000 1000",
    states: [
        {
            name: "Gros Islet",
            code: "LC06",
            path: "M501.7 202l8.7-40.4 8.9-15.9 54.3-78.2 31.4-22 43 14.1-10 39.5 14.9 20.5 24.2 14-32.1 20.4-27.8 25.8-11.1 37.3-5.8 43.4-49.9-8.9-16.7-28.7-32-20.9z"
        },
        {
            name: "Castries",
            code: "LC02",
            path: "M501.7 202l32 20.9 16.7 28.7 49.9 8.9-2.6 19.8-8.3 68.8-14 57.4-22.2 60.3-8.4 63.1 0 48.7-25.1-8.6-19.4-22.9 0-43.1 0-28.6-2.8-48.8-5.6-45.9-16.7-28.7-39-8.6-38.1-12.8 54.1-81.9 11.6-9.2 21.6-12.3 11.1-11 5.2-14.2z"
        },
        {
            name: "Anse-la-Raye",
            code: "LC01",
            path: "M398.1 330.6l38.1 12.8 39 8.6 16.7 28.7 5.6 45.9 2.8 48.8 0 28.6 0 43.1-5.6 43-16.7 17.2-44.6-11.5-30.6-51.6-36.2-25.8-33.4-8.6-24.6 0.2 4.4-19 12.1-31.9 53.1-77.1 19.9-51.4z"
        },
        {
            name: "Soufrière",
            code: "LC10",
            path: "M500.3 547.1l19.4 22.9 25.1 8.6 0 23-8.3 54.4-24.2 13.6-14.2 8-22.9 12.8-75.2 28.7-52.9 25.8-41.2 32.4-13.5-15-8.7-17.3 15.4-35.9 2.5-23.2-2.5-45-3.5-14.7-6.3-11.6-5.6-14.5-0.9-23.3 5.8-24.2 20-42.6 24.6-0.2 33.4 8.6 36.2 25.8 30.6 51.6 44.6 11.5 16.7-17.2 5.6-43z"
        },
        {
            name: "Choiseul",
            code: "LC03",
            path: "M305.9 777.3l41.2-32.4 52.9-25.8 75.2-28.7 22.9-12.8 1.5 11.3-10.5 6.8-7 19.3-27.4 62.8-24.2 48.2-15.3 33.5-65-25.4-37.2-44.8-7.1-12z"
        },
        {
            name: "Laborie",
            code: "LC07",
            path: "M415.2 859.5l15.3-33.5 24.2-48.2 27.4-62.8 7-19.3 10.5-6.8 1.2 10 7.8 29.8 14.9 51.5 14 34.6 2.4 46.6 0.7 31.4-10.3 25.2-13.9-19.1-101.2-39.4z"
        },
        {
            name: "Vieux Fort",
            code: "LC11",
            path: "M498.1 677.6l14.2-8 29.7 35.2 44.6 48.7 27.8 31.6 24.9 33.8-10.7 2.9-9.5 6.4-10.3 21.9-20 87.4-13.9 13.3-6.8 3.7-11.1 0-26.7-36.5 10.3-25.2-0.7-31.4-2.4-46.6-14-34.6-14.9-51.5-7.8-29.8-1.2-10-1.5-11.3z"
        },
        {
            name: "Micoud",
            code: "LC08",
            path: "M512.3 669.6l24.2-13.6 47.3 11.5 61.2 17.2 51.7-1.3-27.6 112-5.9 15.8-6.7 2.8-17.2 4.9-24.9-33.8-27.8-31.6-44.6-48.7-29.7-35.2z"
        },
        {
            name: "Praslin",
            code: "LC09",
            path: "M544.8 578.6l0-48.7 47.3-8.6 39 14.3 33.4-17.2 36.6-7.2-10.8 71.2 6.4 101-51.7 1.3-61.2-17.2-47.3-11.5 8.3-54.4 0-23z"
        },
        {
            name: "Dennery",
            code: "LC05",
            path: "M544.8 529.9l8.4-63.1 22.2-60.3 14-57.4 44.5-5.7 41.8-2.9 41.5 5.6-0.2 59.9-15.9 105.2-36.6 7.2-33.4 17.2-39-14.3-47.3 8.6z"
        },
        {
            name: "Dauphin",
            code: "LC04",
            path: "M600.3 260.5l5.8-43.4 11.1-37.3 27.8-25.8 32.1-20.4 17.9 20 6.1 28.5 7.6 96.5 8.5 67.5-41.5-5.6-41.8 2.9-44.5 5.7 8.3-68.8 2.6-19.8z"
        }
    ],
    labels: [
        {
            code: "LC06",
            x: "583",
            y: "142.7",
            name: "Gros Islet"
        },
        {
            code: "LC02",
            x: "527.5",
            y: "315.3",
            name: "Castries"
        },
        {
            code: "LC01",
            x: "424.3",
            y: "465.6",
            name: "Anse-la-Raye"
        },
        {
            code: "LC10",
            x: "376.7",
            y: "646.4",
            name: "Soufrière"
        },
        {
            code: "LC03",
            x: "399.6",
            y: "777.3",
            name: "Choiseul"
        },
        {
            code: "LC07",
            x: "488",
            y: "825.6",
            name: "Laborie"
        },
        {
            code: "LC11",
            x: "579.9",
            y: "813.1",
            name: "Vieux Fort"
        },
        {
            code: "LC08",
            x: "619.1",
            y: "725.8",
            name: "Micoud"
        },
        {
            code: "LC09",
            x: "622.1",
            y: "605.3",
            name: "Praslin"
        },
        {
            code: "LC05",
            x: "638.9",
            y: "442.4",
            name: "Dennery"
        },
        {
            code: "LC04",
            x: "654.1",
            y: "256.4",
            name: "Dauphin"
        }
    ]
}

export default SAINT_LUCIA
