/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const SAINT_MARTIN_FRENCH = {
    name: "Saint_martin_french",
    code: "MF",
    viewBox: "0 0 1000 686",
    states: [
        {
            name: "St-Martin",
            code: "MF",
            path: "M908.9 654.7l-456.3-176.5-141.1-25.3 0-34-55.4 11.1-101.7 36-25.5 5.5-63.6-36.6-19.8-39.5 21.4-27.1 199.5-3.5 118-29.1 82-64.3 31.6-114.1 54.9-40.9 125.2-48 138.4-35.5 91.8-1.7-1.9 151.8 45.7 209.3 2.4 210.1-45.6 52.3z"
        }
    ],
    labels: [
        {
            code: "MF",
            x: "696.3",
            y: "318.1",
            name: "St-Martin"
        }
    ]
}

export default SAINT_MARTIN_FRENCH
