/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const SAINT_VINCENT_AND_THE_GRENADINES = {
    name: "Saint_vincent_and_the_grenadines",
    code: "VC",
    viewBox: "0 0 1000 1000",
    states: [
        {
            name: "Grenadines",
            code: "VC06",
            path: "M609 438.8l-16 15.5-20.1 34.4-17.8 12.5 8.3 0-8.3 8.5-5.7-8.4-8.9-5.2-11.3-2.3-12.9 0.3 0-8.5 16.6 5.2 25.3-5.1 0-9.2-7.3-8.4-3.4-5.9 9.2-9 31-20.1 12.9-10.7 1.6 4.4 0.5 4.2 1.6 3.9 4.7 3.9z m-275.5 489.8l13.4 8.4 3.1 9.9-6.8 4.6-11.7 3-14.1-1-4.4-6.1 4.6-5.9 1.2-4.8-2.4-4.2 1.4-3 8-3.2 7.7 2.3z m135.9-143.7l3.4 4.3 2.2 10.4-6 8-6.4 6.5-3.2 10-6.2 6.7-11.3 0.6-10.1-3.9 2.8-3.5 12.6-2.8 5.9-7.5-2.1-10.1 0.6-11.2 10-6.7 7.8-0.8z m142.1-153.5l9.5-17.4 9.2 1.9-9.6 22.6-4.5 6.4-3.6 0.6-1-14.1z"
        },
        {
            name: "Saint Andrew",
            code: "VC02",
            path: "M560.1 294.2l-37.2-26.5 14.3-15.4 22.6-16.5 20.4-22.5 8.8-3.7 14.6-2.3-1.5 18.8 8.2 7.1-6.7 13.9-24.8 27.7-18.7 19.4z"
        },
        {
            name: "Saint George",
            code: "VC04",
            path: "M560.1 294.2l18.7-19.4 24.8-27.7 6.7-13.9 5.7 4.9 14.6 10.4 13.1-2.2 16.8 3 13.6 5.4-2.8 12.5-32.6 46.7-19.9 15.5-27.9-13.3-30.8-21.9z"
        },
        {
            name: "Charlotte",
            code: "VC01",
            path: "M610.3 233.2l-8.2-7.1 1.5-18.8 4.4-11.2 8-15.8 14.6 3 2.9-15 1.5-21.7-1.5-18.8-0.7-15.7 3.6-21 9.5-1.5-0.7-15-11-4.5 0.1-23.7 22.3 3.6 8 3.1 4.5 7.7 6.9 16.7 11 50.9-0.5 70.1-12.4 56.2-13.6-5.4-16.8-3-13.1 2.2-14.6-10.4-5.7-4.9z"
        },
        {
            name: "Saint David",
            code: "VC03",
            path: "M634.3 46.4l-0.1 23.7 11 4.5 0.7 15-9.5 1.5-3.6 21 0.7 15.7 1.5 18.8-1.5 21.7-2.9 15-14.6-3-14.6-15-15.3 13.5-14.9 10.2-24.6-5.7-20.4-6.4 6-12.1-2.9-4.3-5.4-11.3 30.1-4.9 12.8-25.8 7.7-33 14.4-26.4 14.4-9.4 13.3-3.9 12-0.3 5.7 0.9z"
        },
        {
            name: "Saint Patrick",
            code: "VC05",
            path: "M603.6 207.3l-14.6 2.3-8.8 3.7-20.4 22.5-22.6 16.5-14.3 15.4-9-33.6 3-38.9 9.3-18.3 20.4 6.4 24.6 5.7 14.9-10.2 15.3-13.5 14.6 15-8 15.8-4.4 11.2z"
        }
    ],
    labels: [
        {
            code: "VC06",
            x: "569.4",
            y: "463.8",
            name: "Grenadines"
        },
        {
            code: "VC02",
            x: "570.9",
            y: "253.2",
            name: "Saint Andrew"
        },
        {
            code: "VC04",
            x: "619.8",
            y: "282.1",
            name: "Saint George"
        },
        {
            code: "VC01",
            x: "647.9",
            y: "212.6",
            name: "Charlotte"
        },
        {
            code: "VC03",
            x: "599.1",
            y: "129.8",
            name: "Saint David"
        },
        {
            code: "VC05",
            x: "545.5",
            y: "212.2",
            name: "Saint Patrick"
        }
    ]
}

export default SAINT_VINCENT_AND_THE_GRENADINES
