/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const SINGAPORE = {
    name: "Singapore",
    code: "SG",
    viewBox: "0 0 1000 508",
    states: [
        {
            name: "South West",
            code: "SG05",
            path: "M562.7 465.7l-7.2 8.6-13 5.6-32.2 4.9-61.1-1.2-30.2-7.8-12.8-15-21.4-34.3-52-23.9-62.6-14.5-53.6-5.8-108.8 2.8-44.2-10.8-18.1-34.6 10.8-39.6 74.7-105.9 10.8-47.4 12.5-26.7 28.1-28.6 33.2-20.2 24.1-4 54.6 7.2 56.2-7.2-2.9 24.2-4.9 27.5-1.6 21.1 0 29.2 13 17.8 17.8 17.9 17.8 14.6 24.3 19.4 1.7 16.2-9.8 11.4-9.7 9.7 4.9 11.4 19.4 6.5 19.5 16.2 21 22.7 3.3 32.4-1.6 21.1 6.4 24.3 24.4 25.9 22.6 13 29.2 11.3 17.4 4.6z"
        },
        {
            name: "Central Singapore",
            code: "SG01",
            path: "M562.7 465.7l-17.4-4.6-29.2-11.3-22.6-13-24.4-25.9-6.4-24.3 1.6-21.1-3.3-32.4 21.1-16.2 22.7-22.7 0-26-11.3-17.8 12.9-19.5 26-14.6 19.4-16.2-3.2-19.4-9.8-19.5-16.2-17.8 6.5-21.1 19.5-19.5 22.7-1.6 30.8 1.6 29.1-3.2 17.9-21.3 70.1 35-11.8 15.5-9.7 24.3-4.9 25.9-21 8.1-16.3 8.2-17.8 17.8-9.7 24.3 0 24.3 4.8 26 14.6 24.3 17.9 27.5 17.8 29.2 7.7 13.6-26 9.9-87.7 60.1-14.4 13.4z"
        },
        {
            name: "South East",
            code: "SG04",
            path: "M690.8 382.3l-7.7-13.6-17.8-29.2-17.9-27.5-14.6-24.3-4.8-26 0-24.3 9.7-24.3 17.8-17.8 16.3-8.2 21-8.1-3.2 29.2 21.1 16.2 27.5 9.8 32.4 14.6 13 11.3 17.8 0 8.1-27.6 0-19.4 22.7-9.7 19.5-16.3 8.6-17 49.8 11.3 34.7 12.8 9.7 15.4-28.9 48.2-42.6 51.3-51.3 41-56.3 16.6-61.7 6.8-22.9 8.8z"
        },
        {
            name: "North East",
            code: "SG02",
            path: "M692.8 179l4.9-25.9 9.7-24.3 11.8-15.5 57.6 28.8 71 25.1 12.5 2.9-8.6 17-19.5 16.3-22.7 9.7 0 19.4-8.1 27.6-17.8 0-13-11.3-32.4-14.6-27.5-9.8-21.1-16.2 3.2-29.2z"
        },
        {
            name: "North West",
            code: "SG03",
            path: "M461 333.1l-21-22.7-19.5-16.2-19.4-6.5-4.9-11.4 9.7-9.7 9.8-11.4-1.7-16.2-24.3-19.4-17.8-14.6-17.8-17.9-13-17.8 0-29.2 1.6-21.1 4.9-27.5 2.9-24.2 69.7-33.3 37.3-10.9 66.6 3.9 64.2 21 60.8 30.3-17.9 21.3-29.1 3.2-30.8-1.6-22.7 1.6-19.5 19.5-6.5 21.1 16.2 17.8 9.8 19.5 3.2 19.4-19.4 16.2-26 14.6-12.9 19.5 11.3 17.8 0 26-22.7 22.7-21.1 16.2z"
        },

    ],
    labels: [
        {
            code: "SG05",
            x: "256.2",
            y: "263.3",
            name: "South West"
        },
        {
            code: "SG01",
            x: "569",
            y: "351",
            name: "Central Singapore"
        },
        {
            code: "SG04",
            x: "721.4",
            y: "300.4",
            name: "South East"
        },
        {
            code: "SG02",
            x: "763.1",
            y: "190.3",
            name: "North East"
        },
        {
            code: "SG03",
            x: "435.5",
            y: "140.1",
            name: "North West"
        }
    ]
}

export default SINGAPORE
