/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const TONGA = {
    name: "Tonga",
    code: "TO",
    viewBox: "0 0 1000 1000",
    states: [
        {
            name: "Vava'u",
            code: "TO05",
            path: "M628.1 444.3l1.9 0.7 0.9 0.9 0.8 1 1.6 1.1 0.2 1.5-0.2 2.7-0.9 1.4-2.5-2.8-1.3 0.6-0.8 0.8 0.2 1 1.1 1.2-1.1 1.3-0.7 1.4-1.7-0.4-1.2 1.4-0.6 2.3 0 2.3-1.6-0.9-0.9-1.5-0.9-3.2 2-0.8 0.1-1.5-0.7-1.6-0.6-0.6-1.4 1.2-0.5 2-0.5 1.3-1.9-0.9-0.2 0.8-0.3 0.1-0.6 0-0.7 0-1.7-3.9 2.4-2 3.6-1.9 1.8-3.6 0.9-0.9 2-0.5 2.3-0.2 1.7 0.2z m-88.4 33.4l-1.3-2.1 0.4-2 1.5-0.9 2 0.7 0.8 1.7-0.4 1.5-1.3 1-1.7 0.1z"
        },
        {
            name: "Eua",
            code: "TO01",
            path: "M506.7 811.7l0.7 5 0 2.1-0.7 5 0.1 8.5-0.8 1.4-2-1.2-0.8-2-1.6-1.7-3.7-2.8 0-0.9 0.5-0.2 1.3-0.7-0.8-1.5-0.1-1.9 0.6-1.6 2.6-1.1 0.8-1 1.2-2.2 0.3-0.9 0.9-2 1-1.4 0.5 1.1z"
        },
        {
            name: "Tongatapu",
            code: "TO04",
            path: "M487.5 788.8l1.4 1 0.5 1.1-0.1 2.1-1.1 1.2-7.2 5.3-0.5 1.2 0.2 1.5 0.5 1.5 0.2 1.4-0.5 1.6-1.1 1-1.4 0.4-1.4 0.3-2.7-0.7-1.3-1.1-2.1-3.9-1.6-1.6-6.1-3-0.9 1-3.2-1.9-1.7-0.7-1.6-0.3-1.2-0.7-3.2-4.4-1.8-3.7 1.2-3.3 3-2.5 3.3-1.1-1.6 1.9-2 1.7-0.8 1.8 1.8 2 1.4 0.5 1.1 0.1 7.2-1.4 1.2 0.3 0.9 0.8 1 0.6 0.8 0.8 0.3 1.5-1.9 1.2-0.8 1.2 0.5 1.4 1.3 0.5 1.3-0.6 1.3-0.9 1.3-0.5 1.5 0.3 2.3 1.3 1 0.3 1.9-0.5 0.7-1.4 0.8-1.9 1.8-1.8 1.3-0.6 1.6-0.5 1.7-0.1 1.5 0.3z m-145.4 163.7l1.1 0.4 0.8 0.7-0.5 0.6-0.6 0.3-0.4 0-0.7-0.5-0.5-0.7 0.2-0.7 0.6-0.1z"
        },
        {
            name: "Ha'apai",
            code: "TO02",
            path: "M576.8 609.9l1.7-0.6 1.4-1.3 0.9-1.7 0.5-2 0.6 0.1 1.4 0.5 0.5 0.4-1 2.3-0.1 2.7-0.7 2-2.4 0.3-1-0.5-0.8-0.6-0.6-0.7-0.4-0.9z m-89.7-12.1l2 1.6 0.9 3.7-0.2 4.1-1.5 2.7 0-1-0.8 1-0.6-0.8-0.6-0.5-1.5-0.6 0.1 0-0.2-0.4 0.1-0.5-1.6-4.2-0.1-1.3 0.5-2.6 0.8-1.1 1.1-0.1 1.6 0z m96.7 2.9l2.3-1.3 1.2-1.7 1.1-1.9 1.6-1.6 0.6 1.9-0.4 1.8-0.7 1.6-0.4 1.6-0.9 1.7-2.1 0.2-1.8-0.8-0.5-1.5z m5.7-13.8l1.7 0.7 0.5 1.4-0.7 1-1.9-0.4-1.4-2-1.7-3.3-0.5-2.5 1.9 0.4 0.6 1.1 0.7 3 0.8 0.6z"
        },
        {
            name: "Niuas",
            code: "TO03",
            path: "M415.8 45.5l2.4 1.8-0.6 3.7-2.8 3-3.7-0.4-2.2-2.5 0.3-2.7 2.5-2.1 4.1-0.8z m240.6 50l1.6-1 0.7 0-0.1 1.8-1.4 2.3-1.8 1.8-2 0-1.1-1.4 0.1-1 1.3-1.2 2.7-1.3z"
        }
    ],
    labels: [
        {
            code: "TO05",
            x: "624.7",
            y: "449.1",
            name: "Vava'u"
        },
        {
            code: "TO01",
            x: "503",
            y: "822.1",
            name: "Eua"
        },
        {
            code: "TO04",
            x: "475.2",
            y: "800.5",
            name: "Tongatapu"
        },
        {
            code: "TO02",
            x: "486.8",
            y: "603.2",
            name: "Ha'apai"
        },
        {
            code: "TO03",
            x: "413.5",
            y: "49.9",
            name: "Niuas"
        }
    ]
}

export default TONGA
