/**********************************************************************************************
 *                                                                                            *
 *  ██████╗  ██████╗     ███╗   ██╗ ██████╗ ████████╗    ███████╗██████╗ ██╗████████╗         *
 *  ██╔══██╗██╔═══██╗    ████╗  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██║╚══██╔══╝         *
 *  ██║  ██║██║   ██║    ██╔██╗ ██║██║   ██║   ██║       █████╗  ██║  ██║██║   ██║            *
 *  ██║  ██║██║   ██║    ██║╚██╗██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║            *
 *  ██████╔╝╚██████╔╝    ██║ ╚████║╚██████╔╝   ██║       ██████║ ██████╔╝██║   ██║            *
 *  ╚═════╝  ╚═════╝     ╚═╝  ╚═══╝ ╚═════╝    ╚═╝       ╚═════╝ ╚═════╝ ╚═╝   ╚═╝            *
 *                                                                                            *
 *  ████████╗██╗  ██╗██╗███████╗    ███████╗██╗██╗     ███████╗                               *
 *  ╚══██╔══╝██║  ██║██║██╔════╝    ██╔════╝██║██║     ██╔════╝                               *
 *     ██║   ███████║██║███████╗    █████╗  ██║██║     █████╗                                 *
 *     ██║   ██╔══██║██║╚════██║    ██╔══╝  ██║██║     ██╔══╝                                 *
 *     ██║   ██║  ██║██║███████║    ██║     ██║███████╗███████╗                               *
 *     ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚══════╝                               *
 *                                                                                            *
 **********************************************************************************************
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE.  🚨🚨🚨 *
 *                                                                                            *
 *  THIS FILE IS AUTO-GENERATED AND PART OF THE LIBRARY.                                      *
 *  IT IS PROVIDED AS-IS AND IS SUBJECT TO CHANGE WITHOUT NOTICE.                             *
 *                                                                                            *
 *  IF YOU EDIT, CHANGE, OR MODIFY THIS FILE IN ANY WAY, YOUR CHANGES WILL BE                 *
 *  OVERWRITTEN AND PERMANENTLY LOST THE NEXT TIME YOU UPDATE THE LIBRARY.                    *
 *  THE UPDATE PROCESS WILL REPLACE THIS ENTIRE FILE, AND ALL YOUR CUSTOMIZATIONS              *
 *  WILL BE REVERTED.                                                                         *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ✅ THE CORRECT WAY TO CUSTOMIZE:                                                          *
 *                                                                                            *
 *  DO NOT EDIT THIS FILE. INSTEAD, IMPORT IT INTO YOUR OWN PROJECT AND OVERRIDE              *
 *  THE PROPERTIES YOU NEED. FOR EXAMPLE:                                                     *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      japanData.code = "JPP";                                                               *
 *                                                                                            *
 *  YOU CAN ALSO CLONE THE OBJECT AND MODIFY THE CLONE, OR CREATE A NEW OBJECT                *
 *  THAT EXTENDS OR WRAPS THIS ONE.                                                           *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  ❌ WHAT NOT TO DO:                                                                        *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // export const JAPAN = { ... };  // with your own edits inside this file             *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Change the code, name, viewBox, or states directly in this file.                   *
 *                                                                                            *
 *      // DO NOT DO THIS:                                                                    *
 *      // Commit changes to this file to your repository.                                    *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📌 WHY?                                                                                   *
 *                                                                                            *
 *  THIS FILE IS MAINTAINED BY THE LIBRARY AUTHORS.                                           *
 *  WHEN A NEW VERSION IS RELEASED, THIS FILE IS REPLACED WITH THE LATEST DATA.               *
 *  ANY LOCAL CHANGES YOU MAKE WILL BE LOST.                                                  *
 *  TO KEEP YOUR CUSTOMIZATIONS, ALWAYS WORK IN YOUR OWN FILES.                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  📁 RECOMMENDED PATTERN:                                                                   *
 *                                                                                            *
 *  Create a new file in your project, e.g. `my-japan.js`:                                    *
 *                                                                                            *
 *      import japanData from "./maps/japan";                                                 *
 *                                                                                            *
 *      const myJapan = {                                                                     *
 *          ...japanData,                                                                     *
 *          code: "JPP",                                                                      *
 *          // add your custom states, name, viewBox, etc.                                    *
 *      };                                                                                    *
 *                                                                                            *
 *      export default myJapan;                                                               *
 *                                                                                            *
 *  Then import `myJapan` wherever you need it.                                               *
 *                                                                                            *
 *  ────────────────────────────────────────────────────────────────────────────────────────  *
 *                                                                                            *
 *  🔒 THIS FILE IS LOCKED FOR A REASON. RESPECT THE LOCK.                                    *
 *                                                                                            *
 *  🚨🚨🚨  DO NOT EDIT THIS FILE. DO NOT CHANGE THIS FILE. DO NOT MODIFY THIS FILE 🚨🚨🚨 *
 *                                                                                            *
 **********************************************************************************************/
const TURKS_AND_CAICOS_ISLANDS = {
    name: "Turks_and_caicos_islands",
    code: "TC",
    viewBox: "0 0 1000 532",
    states: [
        {
            name: "Providenciales and West Caicos",
            code: "TCX03",
            path: "M59.3 208l18.3-2.8 0.2 21.1-12.7 25.4-19.6 10.6 0-4.5 7.4-7.5 4.6-13 2-15.3-0.2-14z m83-69.2l-2-9.4 7-22.8-0.4-12.3 15.1 7.4 42.3 39.3 8.9 3.3 13.2 0 13.1-2.3 8.8-3.2 9.6-9.3 5.5-7.7 7.2-1.9 14.8 8.6 0 5.4-17.9 17.3-5.4 6.9-3.5-10.5-0.7-4.3-18.8 9.9 2.5 0.8 2.3 0.5 2.2 1.1 2.2 2.5-10 5.4-17-2.5-9.8 2.5 0-10.3-26.6 21.5-12.1 1.8-7.5-18.4 4.1 0 4.2 6.2 6.3 3.1 4.7-1.5-0.6-7.8-4.1-3.8-23.4-11 2.2 9.9-1.7 7.4-5.6 5.1-9.1 2.8-1.5-4.8-0.4-3.3 0.6-3.1 1.3-4.1 1.1 3.1 0.3 0.5 0.7 0 2.5 1.3 2.6-9.5 8.5-15.6 2.7-9.5-14.5 11.3-3.9 4z m142.7-38.8l3.7-2.4 2.1 3-5.4 5-5.8-0.6 5.4-5z m20.3-20.2l3.5-2.2 1.7 3.3 0 5.9-4 4.1-4.5 1.9-1.3-5.2 4.6-7.8z"
        },
        {
            name: "South Caicos and East Caicos",
            code: "TCX04",
            path: "M699.7 208l-14-8.7-29.8-12.9-11.7-13.4 3.1-2.2 2.8-1.1 2.2-1.9 1.5-4.3 22.3 14.7 11.8 4.9 16.4 4.7 13.6 5.7 12.9 10.6 6.6 14.9-5.1 18.6-7.9 1.7-9.5-9.6-15.2-21.7z m-120.9 293l5.1-3.3 4.2-1.5-3.1 5.5-11.6 6.3-2.1-1.3 7.5-5.7z m36-13.7l3.7-4 0.4 10.2-4.3 11.3-4.2-6.1 4.4-11.4z m91.4-181l1.4 4.4-0.6 23.9 0.6 16.5-5.4 9.7-11.2 3.4-11.2-7.3-1.4-12.4 8-5.6 8.1 1.2 4.6-3.7 0.1-17.2 4.8-12.6 2.2-0.3z"
        },
        {
            name: "Middle Caicos",
            code: "TCX01",
            path: "M501.5 148.3l-16.7 1.5-5.2-4.1-6-11.8-2.4-8.4-1.8-26.7 5.6 0.4 5.7 1.3 5.4 2.3 11 7.8 6.4 0 6.1-1.7 6.1-0.6 41.3 5.3 19.2-3.9 8.7-0.5 8.8 4.4 7.1 9.1 16.3 35.4-11.5-3.8-7.4-10.1-6.1-11.7-7.5-9 5.4 16.2 12.6 25.2 4.9 13.4-9 1.8-6.7-4.7-11.8-17.3-4 7.4-1 3-4.2 0-10.5-19.8-17.3-5.5-41.5 5.1z"
        },
        {
            name: "North Caicos",
            code: "TCX02",
            path: "M354.2 63.8l-2.8-6.8 1.1-7.1-0.3-6.4-7.6-4.5 3-5.6 4.3-4.4 5.4-3.2 6.1-1.6 39.2 0 4 0.8 9.1 3.7 5.3 0.9 7.8 2.4 1.5 5.8-2.2 11.1 5.8 42.5 10 14.7 20.9 2.2-13.3 10.7-11.7-2.8-10.1-7.9-8.7-4.5-5.7-1.8-8-4.6-7.6-6.3-4.2-7.1 0.9-9.5 10.3-16.9 2.6-8.7-5.1-12.6-11 6.6-16.1 18.6-2.7 5.7-6.5 1.5-7.7-1.5-6-3.4z"
        },
        {
            name: "Grand Turk",
            code: "TCX05",
            path: "M948.4 346.6l5.2 11.3 0.9 18.6-3.1 18.6-7.6 10.8-4.6-13.7 0.5-16.1 3.7-16 5-13.5z"
        },
        {
            name: "Salt Cay",
            code: "TCX06",
            path: "M900.1 471l6.6 0.3 5.1 4.3-5.9 8.6-8.4 9-3.7-2.7 3.4-13.3 2.9-6.2z"
        }
    ],
    labels: [
        {
            code: "TCX03",
            x: "185.9",
            y: "141.8",
            name: "Providenciales and West Caicos"
        },
        {
            code: "TCX04",
            x: "714.9",
            y: "208.6",
            name: "South Caicos and East Caicos"
        },
        {
            code: "TCX01",
            x: "535.2",
            y: "127.5",
            name: "Middle Caicos"
        },
        {
            code: "TCX02",
            x: "415.1",
            y: "77",
            name: "North Caicos"
        },
        {
            code: "TCX05",
            x: "947.1",
            y: "376.5",
            name: "Grand Turk"
        },
        {
            code: "TCX06",
            x: "902",
            y: "480.2",
            name: "Salt Cay"
        }
    ]
}

export default TURKS_AND_CAICOS_ISLANDS
